#!/bin/bash
# Usage: dotfiles
# Philip Pesca

err() {
    errno=$1
    msg=$2

    echo "error: $msg" >&2
    exit $errno
}

if [[ "$0" != "./dotfiles" ]]; then
    err 1 "please install from the dotfiles directory."
fi

if [[ -d backup ]]; then
    rm -d backup > /dev/null 2> /dev/null
    if [[ $? != 0 ]]; then
        err 2 "backup directory must be empty."
    fi
else
    echo "Creating backup directory..."
    mkdir backup
fi

for d in dot.*; do
    path="$HOME/$(echo $d | cut -c4-)"
    if [[ -e $path ]]; then
        echo "Backing up $(basename $path)..."
        cp $path backup/$d
    fi
done

for d in dot.*; do
    path="$HOME/$(echo $d | cut -c4-)"
    if [[ -f $path || -h $path ]]; then
        echo "Removing $(basename $path)..."
        rm $path
    fi
done

for d in dot.*; do
    path="$HOME/$(echo $d | cut -c4-)"
    echo "Linking $(basename $path)..."
    ln -s $(pwd)/$d $path
done

